from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import PostViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'posts', PostViewSet) # This will create URLs like /api/admin/posts/

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)), # Include all URLs generated by the router
]