# bolbhiduback/messages_app/urls.py
# This file defines the URL routing specifically for the messages_app.

from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import MessageViewSet

# Create a router and register our viewsets with it.
router = DefaultRouter()
router.register(r'messages', MessageViewSet) # This will create URLs like /api/messages/

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path('', include(router.urls)), # Include all URLs generated by the router
]
